"""UI for control window"""

# This file is part of ProChem.
# ProChem Copyright (C) 2021-2025 A.A.Solovykh - https://github.com/asolovykh
# See LICENSE.txt for details.


from PySide6.QtCore import (QCoreApplication, QLocale, QObject, QRect, QSize, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QCursor, QFont, QIcon, QPalette)
from PySide6.QtWidgets import (QMainWindow, QComboBox, QFrame, QGridLayout, 
    QHBoxLayout, QLabel, QLineEdit, QMenu, QMenuBar, QPushButton, QSizePolicy, 
    QSlider, QSpacerItem, QTabWidget, QVBoxLayout, QWidget, QTreeView, 
    QAbstractItemView, QHeaderView)
from gui.tree_view_model import CustomTreeModel
import os
import gui.resource_rc

__all__ = ["Ui_Control"]


class Ui_Control(object):
    def setupUi(self, Control):
        if not Control.objectName():
            Control.setObjectName("Control")
        Control.setWindowModality(Qt.NonModal)
        Control.resize(480, 212)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Control.sizePolicy().hasHeightForWidth())
        Control.setSizePolicy(sizePolicy)
        Control.setMinimumSize(QSize(480, 252))
        Control.setMaximumSize(QSize(720, 418))
        Control.setContextMenuPolicy(Qt.DefaultContextMenu)
        Control.setAcceptDrops(False)
        Control.setWindowIcon(QIcon(":/icons/logo/PROCHEM-logo.ico"))
        Control.setAutoFillBackground(False)
        
        style_sheet = ""
        with open(os.path.join(os.path.dirname(__file__), "style_sheets", "control.css")) as file:
            style_sheet = file.read()
        Control.setStyleSheet(style_sheet)
        Control.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        Control.setInputMethodHints(Qt.ImhNone)
        Control.setIconSize(QSize(24, 24))
        Control.setToolButtonStyle(Qt.ToolButtonIconOnly)
        Control.setTabShape(QTabWidget.Rounded)
        Control.setDockNestingEnabled(False)
        Control.setUnifiedTitleAndToolBarOnMac(False)
        self.ALoad_Calculation = QAction(Control)
        self.ALoad_Calculation.setObjectName("ALoad_Calculation")
        font = QFont()
        font.setFamilies(["Times New Roman"])
        font.setPointSize(10)
        self.ALoad_Calculation.setFont(font)
        self.ALoad_Calculation_State = QAction(Control)
        self.ALoad_Calculation_State.setObjectName("ALoad_Calculation_State")
        self.ALoad_Calculation_State.setFont(font)
        self.ASave_Calculation_State = QAction(Control)
        self.ASave_Calculation_State.setObjectName("ASave_Calculation_State")
        self.ASave_Calculation_State.setFont(font)
        self.ALoad_Configuration = QAction(Control)
        self.ALoad_Configuration.setObjectName("ALoad_Configuration")
        self.ALoad_Configuration.setFont(font)
        self.ASave_Configuration = QAction(Control)
        self.ASave_Configuration.setObjectName("ASave_Configuration")
        self.ASave_Configuration.setFont(font)
        self.AExit = QAction(Control)
        self.AExit.setObjectName("AExit")
        self.AExit.setFont(font)
        self.AAxes = QAction(Control)
        self.AAxes.setObjectName("AAxes")
        self.AAxes.setCheckable(True)
        self.AAxes.setChecked(True)
        self.ACell_boarder = QAction(Control)
        self.ACell_boarder.setObjectName("ACell_boarder")
        self.ACell_boarder.setCheckable(True)
        self.ACell_boarder.setChecked(True)
        self.ABonds = QAction(Control)
        self.ABonds.setObjectName("ABonds")
        self.actionChange_background = QAction(Control)
        self.actionChange_background.setObjectName("actionChange_background")
        self.ADelete_coordinates_after_leave_cell = QAction(Control)
        self.ADelete_coordinates_after_leave_cell.setObjectName("ADelete_coordinates_after_leave_cell")
        self.ADelete_coordinates_after_leave_cell.setCheckable(True)
        self.ADelete_coordinates_after_leave_cell.setChecked(True)
        self.ADelete_coordinates_after_leave_cell.setFont(font)
        self.ALight_1 = QAction(Control)
        self.ALight_1.setObjectName("ALight_1")
        self.ALight_1.setFont(font)
        self.ALight_2 = QAction(Control)
        self.ALight_2.setObjectName("ALight_2")
        self.ALight_2.setFont(font)
        self.ALight_3 = QAction(Control)
        self.ALight_3.setObjectName("ALight_3")
        self.ALight_3.setFont(font)
        self.ALight_4 = QAction(Control)
        self.ALight_4.setObjectName("ALight_4")
        self.ALight_4.setFont(font)
        self.ALight_5 = QAction(Control)
        self.ALight_5.setObjectName("ALight_5")
        self.ALight_5.setFont(font)
        self.ALight_6 = QAction(Control)
        self.ALight_6.setObjectName("ALight_6")
        self.ALight_6.setFont(font)
        self.ALight_7 = QAction(Control)
        self.ALight_7.setObjectName("ALight_7")
        self.ALight_7.setFont(font)
        self.ALight_8 = QAction(Control)
        self.ALight_8.setObjectName("ALight_8")
        self.ALight_8.setFont(font)
        self.AProcessing = QAction(Control)
        self.AProcessing.setObjectName("AProcessing")
        self.AOSZICAR = QAction(Control)
        self.AOSZICAR.setObjectName("AOSZICAR")
        self.APOSCAR = QAction(Control)
        self.APOSCAR.setObjectName("APOSCAR")
        self.ACHGCAR = QAction(Control)
        self.ACHGCAR.setObjectName("ACHGCAR")
        self.AIR_and_RAMAN = QAction(Control)
        self.AIR_and_RAMAN.setObjectName("AIR_and_RAMAN")
        self.AGraphs = QAction(Control)
        self.AGraphs.setObjectName("AGraphs")
        self.AKeyboard = QAction(Control)
        self.AKeyboard.setObjectName("AKeyboard")
        self.AKeyboard.setCheckable(True)
        self.AMouse_keyboard = QAction(Control)
        self.AMouse_keyboard.setObjectName("AMouse_keyboard")
        self.AMouse_keyboard.setCheckable(True)
        self.AAtom_ID = QAction(Control)
        self.AAtom_ID.setObjectName("AAtom_ID")
        self.AAtom_ID.setCheckable(True)
        self.ABond = QAction(Control)
        self.ABond.setObjectName("ABond")
        self.ABond.setCheckable(True)
        self.AValence_angle = QAction(Control)
        self.AValence_angle.setObjectName("AValence_angle")
        self.AValence_angle.setCheckable(True)
        self.AScreenshot = QAction(Control)
        self.AScreenshot.setObjectName("AScreenshot")
        self.AForm_POSCAR = QAction(Control)
        self.AForm_POSCAR.setObjectName("AForm_POSCAR")
        self.AAbout_the_program = QAction(Control)
        self.AAbout_the_program.setObjectName("AAbout_the_program")
        self.AAbout_window = QAction(Control)
        self.AAbout_window.setObjectName("AAbout_window")
        self.ALatest_update = QAction(Control)
        self.ALatest_update.setObjectName("ALatest_update")
        self.AChanges_history = QAction(Control)
        self.AChanges_history.setObjectName("AChanges_history")
        self.ACalculation_State = QAction(Control)
        self.ACalculation_State.setObjectName("ACalculation_State")
        self.ACalculation_State.setEnabled(False)
        self.AProgram_Configuration = QAction(Control)
        self.AProgram_Configuration.setObjectName("AProgram_Configuration")
        self.AProgram_Configuration.setEnabled(False)
        self.ABackground = QAction(Control)
        self.ABackground.setObjectName("ABackground")
        self.AConsole = QAction(Control)
        self.AConsole.setObjectName("AConsole")
        self.AFileSharing = QAction(Control)
        self.AFileSharing.setObjectName("AFileSharing")
        self.actionLight_Settings = QAction(Control)
        self.actionLight_Settings.setObjectName("actionLight_Settings")
        self.APerspective = QAction(Control)
        self.APerspective.setObjectName("APerspective")
        self.APerspective.setCheckable(True)
        self.APerspective.setChecked(True)
        self.AOrthographic = QAction(Control)
        self.AOrthographic.setObjectName("AOrthographic")
        self.AOrthographic.setCheckable(True)
        self.AThreading = QAction(Control)
        self.AThreading.setObjectName("AThreading")
        self.AThreading.setCheckable(True)
        self.AThreading.setChecked(True)
        self.AThreading.setEnabled(False)
        self.AMultiprocessing = QAction(Control)
        self.AMultiprocessing.setObjectName("AMultiprocessing")
        self.AMultiprocessing.setCheckable(True)
        self.AMultiprocessing.setEnabled(False)
        self.LAMMPS_Processing = QAction(Control)
        self.LAMMPS_Processing.setObjectName("LAMMPS_Processing")
        self.SRIM_Processing = QAction(Control)
        self.SRIM_Processing.setObjectName("SRIM_Processing")
        self.VASP_Processing = QAction(Control)
        self.VASP_Processing.setObjectName("VASP_Processing")
        self.VASP_OSZICAR = QAction(Control)
        self.VASP_OSZICAR.setObjectName("VASP_OSZICAR")
        self.VASP_POSCAR = QAction(Control)
        self.VASP_POSCAR.setObjectName("VASP_POSCAR")
        self.VASP_CHGCAR = QAction(Control)
        self.VASP_CHGCAR.setObjectName("VASP_CHGCAR")
        self.VASP_IR_and_RAMAN = QAction(Control)
        self.VASP_IR_and_RAMAN.setObjectName("VASP_IR_and_RAMAN")
        self.MainWidget = QWidget(Control)
        self.MainWidget.setObjectName("MainWidget")
        sizePolicy.setHeightForWidth(self.MainWidget.sizePolicy().hasHeightForWidth())
        self.MainWidget.setSizePolicy(sizePolicy)

        self.gridLayout = QGridLayout(self.MainWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setContentsMargins(-1, 12, -1, -1)
        self.CentralWidget = QWidget(self.MainWidget)
        self.CentralWidget.setObjectName("CentralWidget")
        self.horizontalLayout = QHBoxLayout(self.CentralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ToFirstStep = QPushButton(self.CentralWidget)
        self.ToFirstStep.setObjectName("ToFirstStep")
        font1 = QFont()
        font1.setFamilies(["Times New Roman"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.ToFirstStep.setFont(font1)

        self.horizontalLayout.addWidget(self.ToFirstStep)

        self.MoveBack = QPushButton(self.CentralWidget)
        self.MoveBack.setObjectName("MoveBack")
        font2 = QFont()
        font2.setFamilies(["Times New Roman"])
        font2.setPointSize(14)
        font2.setBold(True)
        self.MoveBack.setFont(font2)

        self.horizontalLayout.addWidget(self.MoveBack)

        self.StepSliderWidget = QFrame(self.CentralWidget)
        self.StepSliderWidget.setObjectName("StepSliderWidget")
        sizePolicy.setHeightForWidth(self.StepSliderWidget.sizePolicy().hasHeightForWidth())
        self.StepSliderWidget.setSizePolicy(sizePolicy)
        self.StepSliderWidget.setAutoFillBackground(False)
        self.StepSliderWidget.setFrameShape(QFrame.Box)
        self.StepSliderWidget.setFrameShadow(QFrame.Sunken)
        self.StepSliderWidget.setLineWidth(3)
        self.StepSliderWidget.setMidLineWidth(1)
        self.verticalLayout_2 = QVBoxLayout(self.StepSliderWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.StepSlider = QSlider(self.StepSliderWidget)
        self.StepSlider.setObjectName("StepSlider")
        font3 = QFont()
        font3.setFamilies(["Times New Roman"])
        font3.setPointSize(12)
        self.StepSlider.setFont(font3)
        self.StepSlider.setAcceptDrops(False)
        self.StepSlider.setAutoFillBackground(False)
        self.StepSlider.setSingleStep(1)
        self.StepSlider.setOrientation(Qt.Horizontal)
        self.StepSlider.setInvertedAppearance(False)
        self.StepSlider.setInvertedControls(False)
        self.StepSlider.setTickPosition(QSlider.TicksBelow)
        self.StepSlider.setTickInterval(5)

        self.verticalLayout_2.addWidget(self.StepSlider)


        self.horizontalLayout.addWidget(self.StepSliderWidget)

        self.MoveForward = QPushButton(self.CentralWidget)
        self.MoveForward.setObjectName("MoveForward")
        self.MoveForward.setFont(font2)

        self.horizontalLayout.addWidget(self.MoveForward)

        self.ToLastStep = QPushButton(self.CentralWidget)
        self.ToLastStep.setObjectName("ToLastStep")
        self.ToLastStep.setFont(font1)

        self.horizontalLayout.addWidget(self.ToLastStep)


        self.gridLayout.addWidget(self.CentralWidget, 5, 0, 1, 4)

        self.TopWidget = QHBoxLayout()
        self.TopWidget.setSpacing(6)
        self.TopWidget.setObjectName("TopWidget")
        self.TopWidget.setContentsMargins(-1, -1, -1, 4)
        
        self.TreeView = QTreeView(self.MainWidget)
        self.TreeView.setObjectName("TreeView")
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.TreeView.setPalette(palette)
        self.TreeView.setFont(font)

        self.TreeModel = CustomTreeModel()
        self.TreeView.setModel(self.TreeModel) 
        self.TreeView.setDragDropMode(QAbstractItemView.InternalMove)
        self.TreeView.setDragEnabled(True)
        self.TreeView.setAcceptDrops(True)
        self.TreeView.setDropIndicatorShown(True)
        self.TreeView.setDefaultDropAction(Qt.MoveAction)
       
        self.TreeView.header().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.TreeView.setColumnWidth(0, 50)
        self.TreeView.header().setSectionResizeMode(1, QHeaderView.ResizeMode.Fixed)
        self.TreeView.setColumnWidth(1, 10)
        self.TreeView.header().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
        self.TreeView.setColumnWidth(2, 360)
        self.TreeView.header().setSectionResizeMode(3, QHeaderView.ResizeMode.Fixed)
        self.TreeView.setColumnWidth(3, 100)
        self.TreeView.header().setStretchLastSection(False)

        self.TreeView.setContextMenuPolicy(Qt.CustomContextMenu)
        
        self.TreeViewContextMenu = QMenu(self.TreeView)
        self.TreeViewContextMenu.setObjectName("TreeViewContextMenu")
        
        self.TreeViewAddCalculation = QAction("Load calculation", self.TreeView)
        self.TreeViewAddCalculation.setObjectName("TreeViewAddCalculation")
        self.TreeViewAddCalculation.setFont(font)
        self.TreeViewContextMenu.addAction(self.TreeViewAddCalculation)

        self.TreeViewHideCalculation = QAction("Hide", self.TreeView)
        self.TreeViewHideCalculation.setObjectName("TreeViewHideCalculation")
        self.TreeViewHideCalculation.setFont(font)
        self.TreeViewContextMenu.addAction(self.TreeViewHideCalculation)

        self.TreeViewDeleteCalculation = QAction("Delete", self.TreeView)
        self.TreeViewDeleteCalculation.setObjectName("TreeViewDeleteCalculation")
        self.TreeViewDeleteCalculation.setFont(font)
        self.TreeViewContextMenu.addAction(self.TreeViewDeleteCalculation) 

        self.TreeView.customContextMenuRequested.connect(self.TreeViewContextMenu.exec)

        self.TopWidget.addWidget(self.TreeView)

        self.TopWidget.setStretch(1, 1)

        self.gridLayout.addLayout(self.TopWidget, 0, 0, 1, 0)

        self.LowerWidget = QWidget(self.MainWidget)
        self.LowerWidget.setObjectName("LowerWidget")
        self.horizontalLayout_2 = QHBoxLayout(self.LowerWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 8, 0, 8)
        self.HSpaser1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.HSpaser1)

        self.SpeedSliderWidget = QFrame(self.LowerWidget)
        self.SpeedSliderWidget.setObjectName("SpeedSliderWidget")
        sizePolicy.setHeightForWidth(self.SpeedSliderWidget.sizePolicy().hasHeightForWidth())
        self.SpeedSliderWidget.setSizePolicy(sizePolicy)
        self.SpeedSliderWidget.setAutoFillBackground(False)
        self.SpeedSliderWidget.setFrameShape(QFrame.Box)
        self.SpeedSliderWidget.setFrameShadow(QFrame.Sunken)
        self.SpeedSliderWidget.setLineWidth(2)
        self.SpeedSliderWidget.setMidLineWidth(1)
        self.verticalLayout = QVBoxLayout(self.SpeedSliderWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.SpeedSlider = QSlider(self.SpeedSliderWidget)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.SpeedSlider.setFont(font3)
        self.SpeedSlider.setAcceptDrops(False)
        self.SpeedSlider.setAutoFillBackground(False)
        self.SpeedSlider.setSingleStep(1)
        self.SpeedSlider.setOrientation(Qt.Horizontal)
        self.SpeedSlider.setInvertedAppearance(False)
        self.SpeedSlider.setInvertedControls(False)
        self.SpeedSlider.setTickPosition(QSlider.TicksBelow)
        self.SpeedSlider.setTickInterval(5)

        self.verticalLayout.addWidget(self.SpeedSlider)


        self.horizontalLayout_2.addWidget(self.SpeedSliderWidget)

        self.HSpacer2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.HSpacer2)

        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)

        self.gridLayout.addWidget(self.LowerWidget, 7, 0, 1, 4)

        self.StepLabelWidget = QHBoxLayout()
        self.StepLabelWidget.setObjectName("StepLabelWidget")
        self.HSpacer3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.StepLabelWidget.addItem(self.HSpacer3)

        self.StepLabel = QLabel(self.MainWidget)
        self.StepLabel.setObjectName("StepLabel")
        self.StepLabel.setAlignment(Qt.AlignCenter)

        self.StepLabelWidget.addWidget(self.StepLabel)

        self.HSpacer4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.StepLabelWidget.addItem(self.HSpacer4)

        self.StepLabelWidget.setStretch(0, 1)
        self.StepLabelWidget.setStretch(1, 5)
        self.StepLabelWidget.setStretch(2, 1)

        self.gridLayout.addLayout(self.StepLabelWidget, 6, 0, 1, 4)

        Control.setCentralWidget(self.MainWidget)
        self.ControlMenubar = QMenuBar(Control)
        self.ControlMenubar.setObjectName("ControlMenubar")
        self.ControlMenubar.setGeometry(QRect(0, 0, 480, 21))
        self.ControlMenubar.setFont(font)
        self.ControlMenuFile = QMenu(self.ControlMenubar)
        self.ControlMenuFile.setObjectName("ControlMenuFile")
        self.ControlMenuFile.setFont(font)
        self.ControlMenuEdit = QMenu(self.ControlMenubar)
        self.ControlMenuEdit.setObjectName("ControlMenuEdit")
        self.ControlMenuEdit.setFont(font)
        self.ControlMenuLight = QMenu(self.ControlMenuEdit)
        self.ControlMenuLight.setObjectName("ControlMenuLight")
        self.ControlMenuLight.setFont(font)
        self.ControlMenuMods = QMenu(self.ControlMenubar)
        self.ControlMenuMods.setObjectName("ControlMenuMods")
        self.ControlMenuMods.setFont(font)
        self.ControlMenuSupercomputer = QMenu(self.ControlMenuMods)
        self.ControlMenuSupercomputer.setObjectName("ControlMenuSupercomputer")
        self.menuVASP = QMenu(self.ControlMenuMods)
        self.menuVASP.setObjectName("menuVASP")
        self.menuVASP.setEnabled(True)
        self.menuLAMMPS = QMenu(self.ControlMenuMods)
        self.menuLAMMPS.setObjectName("menuLAMMPS")
        self.menuLAMMPS.setEnabled(True)
        self.menuSRIM = QMenu(self.ControlMenuMods)
        self.menuSRIM.setObjectName("menuSRIM")
        self.menuSRIM.setEnabled(True)
        self.ControlMenuTools = QMenu(self.ControlMenubar)
        self.ControlMenuTools.setObjectName("ControlMenuTools")
        self.ControlMenuTools.setFont(font)
        self.ControlMenuSelect_mode = QMenu(self.ControlMenuTools)
        self.ControlMenuSelect_mode.setObjectName("ControlMenuSelect_mode")
        self.ControlMenuSelect_mode.setFont(font)
        self.ControlMenuLabel = QMenu(self.ControlMenuTools)
        self.ControlMenuLabel.setObjectName("ControlMenuLabel")
        self.ControlMenuLabel.setFont(font)
        self.ControlMenuHelp = QMenu(self.ControlMenubar)
        self.ControlMenuHelp.setObjectName("ControlMenuHelp")
        self.ControlMenuHelp.setFont(font)
        self.ControlMenuView = QMenu(self.ControlMenubar)
        self.ControlMenuView.setObjectName("ControlMenuView")
        self.menuProjection = QMenu(self.ControlMenuView)
        self.menuProjection.setObjectName("menuProjection")
        self.ControlSettings = QMenu(self.ControlMenubar)
        self.ControlSettings.setObjectName("ControlSettings")
        self.menuParsing_using = QMenu(self.ControlSettings)
        self.menuParsing_using.setObjectName("menuParsing_using")
        Control.setMenuBar(self.ControlMenubar)

        self.ControlMenubar.addAction(self.ControlMenuFile.menuAction())
        self.ControlMenubar.addAction(self.ControlMenuEdit.menuAction())
        self.ControlMenubar.addAction(self.ControlMenuView.menuAction())
        self.ControlMenubar.addAction(self.ControlMenuMods.menuAction())
        self.ControlMenubar.addAction(self.ControlMenuTools.menuAction())
        self.ControlMenubar.addAction(self.ControlSettings.menuAction())
        self.ControlMenubar.addAction(self.ControlMenuHelp.menuAction())
        self.ControlMenuFile.addAction(self.ALoad_Calculation)
        self.ControlMenuFile.addSeparator()
        self.ControlMenuFile.addAction(self.ACalculation_State)
        self.ControlMenuFile.addSeparator()
        self.ControlMenuFile.addAction(self.ALoad_Calculation_State)
        self.ControlMenuFile.addAction(self.ASave_Calculation_State)
        self.ControlMenuFile.addSeparator()
        self.ControlMenuFile.addAction(self.AProgram_Configuration)
        self.ControlMenuFile.addSeparator()
        self.ControlMenuFile.addAction(self.ALoad_Configuration)
        self.ControlMenuFile.addAction(self.ASave_Configuration)
        self.ControlMenuFile.addSeparator()
        self.ControlMenuFile.addAction(self.AExit)
        self.ControlMenuEdit.addAction(self.ADelete_coordinates_after_leave_cell)
        self.ControlMenuEdit.addSeparator()
        self.ControlMenuEdit.addAction(self.ControlMenuLight.menuAction())
        self.ControlMenuEdit.addSeparator()
        self.ControlMenuEdit.addAction(self.ABackground)
        self.ControlMenuLight.addAction(self.ALight_1)
        self.ControlMenuLight.addAction(self.ALight_2)
        self.ControlMenuLight.addAction(self.ALight_3)
        self.ControlMenuLight.addAction(self.ALight_4)
        self.ControlMenuLight.addAction(self.ALight_5)
        self.ControlMenuLight.addAction(self.ALight_6)
        self.ControlMenuLight.addAction(self.ALight_7)
        self.ControlMenuLight.addAction(self.ALight_8)
        self.ControlMenuLight.addSeparator()
        self.ControlMenuLight.addAction(self.actionLight_Settings)
        self.ControlMenuMods.addAction(self.menuVASP.menuAction())
        self.ControlMenuMods.addSeparator()
        self.ControlMenuMods.addAction(self.menuLAMMPS.menuAction())
        self.ControlMenuMods.addSeparator()
        self.ControlMenuMods.addAction(self.menuSRIM.menuAction())
        self.ControlMenuMods.addSeparator()
        self.ControlMenuMods.addAction(self.ControlMenuSupercomputer.menuAction())
        self.ControlMenuMods.addSeparator()
        self.ControlMenuMods.addAction(self.AGraphs)
        self.ControlMenuSupercomputer.addAction(self.AConsole)
        self.ControlMenuSupercomputer.addAction(self.AFileSharing)
        self.menuVASP.addAction(self.VASP_Processing)
        self.menuVASP.addAction(self.VASP_OSZICAR)
        self.menuVASP.addAction(self.VASP_POSCAR)
        self.menuVASP.addAction(self.VASP_CHGCAR)
        self.menuVASP.addAction(self.VASP_IR_and_RAMAN)
        self.menuLAMMPS.addAction(self.LAMMPS_Processing)
        self.menuSRIM.addAction(self.SRIM_Processing)
        self.ControlMenuTools.addAction(self.ControlMenuSelect_mode.menuAction())
        self.ControlMenuTools.addSeparator()
        self.ControlMenuTools.addAction(self.ControlMenuLabel.menuAction())
        self.ControlMenuTools.addSeparator()
        self.ControlMenuTools.addAction(self.AForm_POSCAR)
        self.ControlMenuTools.addSeparator()
        self.ControlMenuTools.addAction(self.AScreenshot)
        self.ControlMenuSelect_mode.addAction(self.AKeyboard)
        self.ControlMenuSelect_mode.addAction(self.AMouse_keyboard)
        self.ControlMenuLabel.addAction(self.AAtom_ID)
        self.ControlMenuLabel.addAction(self.ABond)
        self.ControlMenuLabel.addAction(self.AValence_angle)
        self.ControlMenuHelp.addAction(self.AAbout_the_program)
        self.ControlMenuHelp.addSeparator()
        self.ControlMenuHelp.addAction(self.AAbout_window)
        self.ControlMenuHelp.addSeparator()
        self.ControlMenuHelp.addAction(self.ALatest_update)
        self.ControlMenuHelp.addSeparator()
        self.ControlMenuHelp.addAction(self.AChanges_history)
        self.ControlMenuView.addAction(self.AAxes)
        self.ControlMenuView.addAction(self.ACell_boarder)
        self.ControlMenuView.addSeparator()
        self.ControlMenuView.addAction(self.menuProjection.menuAction())
        self.ControlMenuView.addSeparator()
        self.ControlMenuView.addAction(self.ABonds)
        self.menuProjection.addAction(self.APerspective)
        self.menuProjection.addAction(self.AOrthographic)
        self.ControlSettings.addAction(self.menuParsing_using.menuAction())
        self.menuParsing_using.addAction(self.AThreading)
        self.menuParsing_using.addAction(self.AMultiprocessing)

        self.retranslateUi(Control)

    def retranslateUi(self, Control):
        Control.setWindowTitle(QCoreApplication.translate("Control", "PROCHEM", None))
        self.ALoad_Calculation.setText(QCoreApplication.translate("Control", "Load calculation", None))
        self.ALoad_Calculation_State.setText(QCoreApplication.translate("Control", "Load", None))
        self.ASave_Calculation_State.setText(QCoreApplication.translate("Control", "Save", None))
        self.ALoad_Configuration.setText(QCoreApplication.translate("Control", "Load", None))
        self.ASave_Configuration.setText(QCoreApplication.translate("Control", "Save", None))
        self.AExit.setText(QCoreApplication.translate("Control", "Exit", None))
        self.AAxes.setText(QCoreApplication.translate("Control", "Axes", None))
        self.ACell_boarder.setText(QCoreApplication.translate("Control", "Cell boarder", None))
        self.ABonds.setText(QCoreApplication.translate("Control", "Bonds", None))
        self.actionChange_background.setText(QCoreApplication.translate("Control", "Change background", None))
        self.ADelete_coordinates_after_leave_cell.setText(QCoreApplication.translate("Control", "Delete coordinates after leave cell", None))
        self.ALight_1.setText(QCoreApplication.translate("Control", "Light 1", None))
        self.ALight_2.setText(QCoreApplication.translate("Control", "Light 2", None))
        self.ALight_3.setText(QCoreApplication.translate("Control", "Light 3", None))
        self.ALight_4.setText(QCoreApplication.translate("Control", "Light 4", None))
        self.ALight_5.setText(QCoreApplication.translate("Control", "Light 5", None))
        self.ALight_6.setText(QCoreApplication.translate("Control", "Light 6", None))
        self.ALight_7.setText(QCoreApplication.translate("Control", "Light 7", None))
        self.ALight_8.setText(QCoreApplication.translate("Control", "Light 8", None))
        self.AProcessing.setText(QCoreApplication.translate("Control", "Processing", None))
        self.AOSZICAR.setText(QCoreApplication.translate("Control", "OSZICAR", None))
        self.APOSCAR.setText(QCoreApplication.translate("Control", "POSCAR", None))
        self.ACHGCAR.setText(QCoreApplication.translate("Control", "CHGCAR", None))
        self.AIR_and_RAMAN.setText(QCoreApplication.translate("Control", "IR and RAMAN", None))
        self.AGraphs.setText(QCoreApplication.translate("Control", "Graphs", None))
        self.AKeyboard.setText(QCoreApplication.translate("Control", "Keyboard", None))
        self.AMouse_keyboard.setText(QCoreApplication.translate("Control", "Mouse+keyboard", None))
        self.AAtom_ID.setText(QCoreApplication.translate("Control", "Atom ID", None))
        self.ABond.setText(QCoreApplication.translate("Control", "Bond", None))
        self.AValence_angle.setText(QCoreApplication.translate("Control", "Valence angle", None))
        self.AScreenshot.setText(QCoreApplication.translate("Control", "Make a screenshot", None))
        self.AForm_POSCAR.setText(QCoreApplication.translate("Control", "Form POSCAR", None))
        self.AAbout_the_program.setText(QCoreApplication.translate("Control", "About the program", None))
        self.AAbout_window.setText(QCoreApplication.translate("Control", "About window", None))
        self.ALatest_update.setText(QCoreApplication.translate("Control", "Latest update", None))
        self.AChanges_history.setText(QCoreApplication.translate("Control", "Changes history", None))
        self.ACalculation_State.setText(QCoreApplication.translate("Control", "Calculation State", None))
        self.AProgram_Configuration.setText(QCoreApplication.translate("Control", "Program Configuration", None))
        self.ABackground.setText(QCoreApplication.translate("Control", "Background", None))
        self.AConsole.setText(QCoreApplication.translate("Control", "Console", None))
        self.AFileSharing.setText(QCoreApplication.translate("Control", "FileSharing", None))
        self.actionLight_Settings.setText(QCoreApplication.translate("Control", "Light Settings", None))
        self.APerspective.setText(QCoreApplication.translate("Control", "Perspective", None))
        self.AOrthographic.setText(QCoreApplication.translate("Control", "Orthographic", None))
        self.AThreading.setText(QCoreApplication.translate("Control", "Threading", None))
        self.AMultiprocessing.setText(QCoreApplication.translate("Control", "Multiprocessing", None))
        self.LAMMPS_Processing.setText(QCoreApplication.translate("Control", "Processing", None))
        self.SRIM_Processing.setText(QCoreApplication.translate("Control", "Processing", None))
        self.VASP_Processing.setText(QCoreApplication.translate("Control", "Processing", None))
        self.VASP_OSZICAR.setText(QCoreApplication.translate("Control", "OSZICAR", None))
        self.VASP_POSCAR.setText(QCoreApplication.translate("Control", "POSCAR", None))
        self.VASP_CHGCAR.setText(QCoreApplication.translate("Control", "CHGCAR", None))
        self.VASP_IR_and_RAMAN.setText(QCoreApplication.translate("Control", "IR and RAMAN", None))
        self.ToFirstStep.setText(QCoreApplication.translate("Control", "<<", None))
        self.MoveBack.setText(QCoreApplication.translate("Control", "<", None))
        self.StepSlider.setToolTip("")
        self.MoveForward.setText(QCoreApplication.translate("Control", ">", None))
        self.ToLastStep.setText(QCoreApplication.translate("Control", ">>", None))
        self.SpeedSlider.setToolTip("")
        self.StepLabel.setText("")
        self.ControlMenuFile.setTitle(QCoreApplication.translate("Control", "File", None))
        self.ControlMenuEdit.setTitle(QCoreApplication.translate("Control", "Edit", None))
        self.ControlMenuLight.setTitle(QCoreApplication.translate("Control", "Light", None))
        self.ControlMenuMods.setTitle(QCoreApplication.translate("Control", "Mods", None))
        self.ControlMenuSupercomputer.setTitle(QCoreApplication.translate("Control", "Supercomputer", None))
        self.menuVASP.setTitle(QCoreApplication.translate("Control", "VASP", None))
        self.menuLAMMPS.setTitle(QCoreApplication.translate("Control", "LAMMPS", None))
        self.menuSRIM.setTitle(QCoreApplication.translate("Control", "SRIM", None))
        self.ControlMenuTools.setTitle(QCoreApplication.translate("Control", "Tools", None))
        self.ControlMenuSelect_mode.setTitle(QCoreApplication.translate("Control", "Selection type", None))
        self.ControlMenuLabel.setTitle(QCoreApplication.translate("Control", "Label", None))
        self.ControlMenuHelp.setTitle(QCoreApplication.translate("Control", "Help", None))
        self.ControlMenuView.setTitle(QCoreApplication.translate("Control", "View", None))
        self.menuProjection.setTitle(QCoreApplication.translate("Control", "Projection", None))
        self.ControlSettings.setTitle(QCoreApplication.translate("Control", "Settings", None))
        self.menuParsing_using.setTitle(QCoreApplication.translate("Control", "Parsing using", None))
